            - name: Run Gemini CLI
  # You may pin to the exact commit or the version.
  # uses: google-github-actions/run-gemini-cli@68d5a6d2e31ff01029205c58c6bf81cb3d72910b
  uses: google-github-actions/run-gemini-cli@v0.1.3
  with:
    # A string passed to the Gemini CLI's [`--prompt` argument](https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/configuration.md#command-line-arguments).
    prompt: # optional, default is You are a helpful assistant.
    # A JSON string written to `.gemini/settings.json` to configure the CLI's _project_ settings.
For more details, see the documentation on [settings files](https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/configuration.md#settings-files).
    settings: # optional
    # The API key for the Gemini API.
    gemini_api_key: # optional
    # The Google Cloud project ID.
    gcp_project_id: # optional
    # The Google Cloud location.
    gcp_location: # optional
    # The Google Cloud Workload Identity Provider.
    gcp_workload_identity_provider: # optional
    # The Google Cloud service account email.
    gcp_service_account: # optional
    # A flag to indicate if Vertex AI should be used.
    use_vertex_ai: # optional, default is false
    # A flag to indicate if Gemini Code Assist should be used.
    use_gemini_code_assist: # optional, default is false
    # The version of the Gemini CLI to install.
    gemini_cli_version: # optional, default is latest
          
